export const API_URL = 'https://painfx.onrender.com/api';

export const ENDPOINTS = {
  LOGIN: "/jwt/create/",
  LOGOUT: "/logout/",
  TOKEN_REFRESH: "/jwt/refresh/",
  REGISTER: "/users/",
  GOOGLE_LOGIN: "/o/google/",
  USER_PROFILE: "/users/me/",
  PATIENTS: "/patients/",
  DOCTORS: "/doctors/",
  CLINICS: "/clinics/",
  RESERVATIONS: "/reservations/",
  REVIEWS: "/reviews/",
  POSTS: "/posts/",
  COMMENTS: "/comments/",
  LIKES: "/likes/",
  CATEGORIES: "/categories/",
  SUBSCRIPTIONS: "/subscriptions/",
  PAYMENT_METHODS: "/payment-methods/",
  PAYMENTS: "/payments/",
  NOTIFICATIONS: "/notifications/",
  EVENT_SCHEDULES: "/event-schedules/",
  ADVERTISING_CAMPAIGNS: "/advertising-campaigns/",
};
