name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Clean up old Buildx instances
      - name: Clean up Buildx Instances
        run: |
          docker buildx ls | grep -q "default" && docker buildx rm default || echo "No default instance to clean up"

      # Step 3: Set up QEMU for multi-architecture builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Step 4: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

  build-django:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx with docker-container driver
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: django-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            django-${{ runner.os }}

      - name: Build and Push Django
        uses: docker/build-push-action@v4
        with:
          context: ./painfx_backend/backend
          push: true
          tags: supernovasoftwareco014/painfx-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-celery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx with docker-container driver
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: celery-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            celery-${{ runner.os }}

      - name: Build and Push Celery
        uses: docker/build-push-action@v4
        with:
          context: ./painfx_backend/infrastructure/celery/celery-worker
          push: true
          tags: supernovasoftwareco014/painfx-celery:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-celery-flower:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx with docker-container driver
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: celery-flower-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            celery-flower-${{ runner.os }}

      - name: Build and Push Celery Flower
        uses: docker/build-push-action@v4
        with:
          context: ./painfx_backend/infrastructure/celery/celery-flower
          push: true
          tags: supernovasoftwareco014/celery-flower:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx with docker-container driver
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: frontend-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            frontend-${{ runner.os }}

      - name: Build and Push Next.js
        uses: docker/build-push-action@v4
        with:
          context: ./painfx_frontend
          push: true
          tags: supernovasoftwareco014/painfx-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: [build-django, build-celery, build-celery-flower, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Copy docker-stack.yml to VPS
        uses: appleboy/scp-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: ./painfx_production/docker-stack.yml
          target: ~/painfx_production/
          timeout: 120s

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.14
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ~/painfx_production
            docker stack deploy -c docker-stack.yml painfx_stack
            echo "Deployment completed successfully!"
