name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Clean up old Buildx instances (Optional)
      - name: Clean up Buildx Instances
        run: docker buildx rm default || true

      # Step 3: Set up QEMU for multi-architecture builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Step 4: Set up Docker Buildx with docker-container driver
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

  build-django:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Push Django
        uses: docker/build-push-action@v4
        with:
          context: ./painfx_backend/backend
          push: true
          tags: supernovasoftwareco014/painfx-backend:latest

  build-celery:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Push Celery
        uses: docker/build-push-action@v4
        with:
          context: ./painfx_backend/infrastructure/celery/celery-worker
          push: true
          tags: supernovasoftwareco014/painfx-celery:latest

  build-celery-flower:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Push Celery Flower
        uses: docker/build-push-action@v4
        with:
          context: ./painfx_backend/infrastructure/celery/celery-flower
          push: true
          tags: supernovasoftwareco014/celery-flower:latest

  build-frontend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Push Next.js
        uses: docker/build-push-action@v4
        with:
          context: ./painfx_frontend
          push: true
          tags: supernovasoftwareco014/painfx-frontend:latest

  deploy:
    needs: [build-django, build-celery, build-celery-flower, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Copy docker-stack.yml to VPS
        uses: appleboy/scp-action@v0.1.8
        with:
          host: ${{ needs.setup.outputs.vps_host }}
          username: ${{ needs.setup.outputs.vps_user }}
          key: ${{ needs.setup.outputs.vps_ssh_key }}
          port: 22
          source: ./painfx_production/docker-stack.yml
          target: ~/painfx_production/docker-stack.yml

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.14
        with:
          host: ${{ needs.setup.outputs.vps_host }}
          username: ${{ needs.setup.outputs.vps_user }}
          key: ${{ needs.setup.outputs.vps_ssh_key }}
          port: 22
          script: |
            cd ~/painfx_production
            docker stack deploy -c docker-stack.yml painfx_stack
